docker:
  image: "iammaxim/j2eo:latest"
  as_root: true
architect:
  - yegor256
assets:
  gradle.properties: yegor256/polystat-secrets#gradle.properties
  pubring.gpg: yegor256/polystat-secrets#pubring.gpg
  secring.gpg: yegor256/polystat-secrets#secring.gpg
  docker-password: yegor256/polystat-secrets#docker-password
install: |
  cp ../gradle.properties .
  wget https://www.antlr.org/download/antlr-4.9.2-complete.jar
merge:
  script: |
    gradle build --info
release:
  script: |-
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1
    gradle build fatJar publish -x test --info -Dcandidates=false -PmvnPublicationVersion=${tag} -Dsigning.secretKeyRingFile=/home/r/secring.gpg
    mv "J2EO-${tag}.jar" j2eo.jar
    image=yegor256/j2eo
    sudo docker build "$(pwd)" --tag "${image}:${tag}"
    cat ../docker-password | sudo docker login --password-stdin --username yegor256
    sudo docker push "${image}:${tag}"