name: Gradle Build

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  gradle:
    strategy:
      matrix:
        os: [
            macos-latest,
            windows-latest
        ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: suisei-cn/actions-download-file@v1.0.1
        name: Download ANTLR
        with:
          url: "https://www.antlr.org/download/antlr-4.10.1-complete.jar"
          target: .

      - uses: gradle/gradle-build-action@v1
        with:
          arguments: build --info
          gradle-version: 7.2

      - name: Upload Gradle test report
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: gradle-test-report-${{ matrix.os }}
          path: build/reports/tests/test/

      - name: Print J2EO test report
        run: |
          cd ./src/test/resources/
          python ./test_report.py

  gradle_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - run: |
          wget https://www.antlr.org/download/antlr-4.10.1-complete.jar

      - uses: gradle/gradle-build-action@v1
        with:
          arguments: build --info
          gradle-version: 7.2

      - name: Upload Gradle test report
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: gradle-test-report-ubuntu-latest
          path: build/reports/tests/test/

      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"

      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: target/site/jacoco/

      - name: Print J2EO test report
        run: |
          cd ./src/test/resources/
          python ./test_report.py
